### ISSUE TITLE
Module Installation Instructions Incorrect

### ISSUE THREAD

**Issue by scovetta** [PowerShell/underhanded-powershell#2]
Two minor bugs on the instructions page:
1- Need to create WindowsPowerShell directory, which doesn't exist by default.
2- Add a semicolon before OutFile (typo).

**Comment by mattifestation** [comment]
Semicolons aren't required when keys are separated by newlines in a hashtable. #1 is a valid point.

**Comment by kapilmb** [comment]
Thanks for the feedback. We have made the changes to the instructions page.
